apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{ values.appName }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ${{ values.appName }}
  template:
    metadata:
      labels:
        app: ${{ values.appName }}
    spec:
      imagePullSecrets:
        - name: harbor-eks-cred 
      containers:
      - name: ${{ values.appName }}
        image: imagerepo.vaw.ai/backstage/${{ values.imagename }}:latest 
        imagePullPolicy: Always
        ports:
        - containerPort: 8090
        env:
        - name: SERVER_PORT
          value: "8090"  # Change application port
