apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app4
spec:
  type: ClusterIP
  selector:
    app: spring-boot-app4
  ports:
    - protocol: TCP
      targetPort: 9090  # Map Kubernetes service to container's port 9090
